### ISSUE TITLE
image recognition

### ISSUE THREAD

**Issue by pam81** [evrythng/scanthng.js#14]
I had created a product with an image and I 'm trying to do an image recognition 
In the doc it says: "for any product through the Dashboard by clicking on "Setup image recognition" on that product's details page"
But I can't find this option.

**Comment by domguinard** [comment]
Hi @pam81 

Thanks for your message. Image recognition is a platform feature that's only available to our Enterprise customers: https://developers.evrythng.com/reference/identifier-recognition#performing-a-scan-or-identification
As far as I can see you have a free-tier account which is why this option is disabled.
